# Generated by Django 3.2.9 on 2021-11-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', 'Admin'), ('R', 'Regular')], default='R', max_length=1)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PET_type', models.CharField(blank=True, choices=[('L', 'Lost'), ('F', 'Found')], max_length=1)),
                ('body_color', models.CharField(blank=True, choices=[('L', 'Lost'), ('F', 'Found')], max_length=3)),
                ('eye_color', models.CharField(blank=True, choices=[('Y', 'yellow'), ('A', 'amber'), ('G', 'grey'), ('GR', 'Green'), ('BL', 'blue'), ('L', 'lightbrown'), ('D', 'darkbrown')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1)),
                ('fixed', models.CharField(blank=True, choices=[('S', 'Spayed'), ('N', 'Neutred'), ('O', 'No')], default='O', max_length=1)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('date_lost', models.DateField(blank=True, null=True)),
                ('date_found', models.DateField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, default='Orlando', max_length=255)),
                ('zip_code', models.CharField(blank=True, default=32819, max_length=15)),
                ('breed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pets.breed')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.employee')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pets.petowner')),
                ('species', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pets.species')),
                ('state', models.ForeignKey(blank=True, default='Fl', on_delete=django.db.models.deletion.PROTECT, to='pets.state')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pets.state'),
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pets.species'),
        ),
    ]
