# Generated by Django 3.2.9 on 2021-11-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], max_length=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_lost', models.DateField()),
                ('date_found', models.DateField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.address')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petowner')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
