# Generated by Django 3.2.9 on 2021-11-21 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='PET_type',
            new_name='pet_type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_color',
            field=models.CharField(blank=True, choices=[('M', 'merle'), ('B', 'brindle'), ('S', 'spotted'), ('BL', 'blue'), ('BK', 'black'), ('SL', 'silver'), ('W', 'white'), ('CR', 'cream'), ('F', 'faWN'), ('L', 'lightbrown'), ('D', 'darkbrown'), ('R', 'red'), ('GT', 'greytabby'), ('RT', 'redtabby'), ('T', 'tuxedo'), ('TT', 'tortiseshell'), ('C', 'calico')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_reported',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
