# Generated by Django 3.2.9 on 2021-11-21 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20211120_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_reported',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
