# Generated by Django 3.2.9 on 2021-11-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
