# Generated by Django 3.2.9 on 2021-11-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20211120_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('A', 'Admin'), ('R', 'Regular')], default='R', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pets.employee'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('L', 'Lost'), ('F', 'Found'), ('D', '---Select Type---')], default='D', max_length=1),
        ),
    ]
