# Generated by Django 3.2.9 on 2021-11-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20211126_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(default='Florida', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='state',
            field=models.CharField(default='Florida', max_length=30),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
