# Generated by Django 3.2.9 on 2021-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20211127_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='fixed',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
