# Generated by Django 3.2.9 on 2021-11-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20211127_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='body_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='eye_color',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
